version: "3.8"

networks:
  tier:
    driver: bridge

services:
  mongodb-initializer:
    image : mongo:6
    networks:
      - tier
    entrypoint:
      - /bin/sh
      - -c
      - |
        sleep 1
#        mongo --host mongodb --eval 'rs.initiate({_id: "rs0", members: [{_id: 0, host: "127.0.0.1:27017"}]})'
    depends_on:
      - mongodb

  mongodb:
    image : mongo:6
    ports:
      - "27017:27017"
    networks:
      - tier
#    command: ["--replSet", "rs0"]
    command: []
